// s:\flutter\src\vtv_common\lib\src\chat\domain\repository.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'chat_repository.dart';