name: vtv_common
description: "A Flutter package project keep all common file for VTV Apps."
version: 0.0.1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # ui
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  timelines: ^0.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: 5.0.1

  # storage
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # notification
  firebase_messaging: ^14.7.17
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.25.4
  fluttertoast: ^8.2.4

  # navigation + state management
  go_router: ^13.0.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7

  # functional
  intl: ^0.19.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  jwt_decoder:
  collection: ^1.18.0
  url_launcher: ^6.3.0

  # network
  http: ^1.2.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.1
  network_info_plus: ^5.0.3
  async: ^2.11.0
  http_parser:

  # others
  stomp_dart_client: ^2.0.0
  logger:

  # analytics
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
