// s:\flutter\src\vtv_common\lib\src\core\config.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'route_observer.dart';
export 'filter_config.dart';