// s:\flutter\src\vtv_common\lib\src\chat\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'dto/dto.dart';
export 'resp/resp.dart';
export 'room_chat_entity.dart';
export 'message_entity.dart';