// s:\flutter\src\vtv_common\lib\src\guest\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'guest_repository.dart';