// s:\flutter\src\vtv_common\lib\src\profile\domain\entities\location.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'district_entity.dart';
export 'address_resp.dart';
export 'province_entity.dart';
export 'ward_entity.dart';