// s:\flutter\src\vtv_common\lib\src\chat.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'src/chat/data/data.dart';
export 'src/chat/domain/domain.dart';
export 'src/chat/presentation/presentation.dart';
