// s:\flutter\src\vtv_common\lib\src\notification\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'notification_entity.dart';
export 'notification_resp.dart';