// s:\flutter\src\vtv_common\lib\src\chat\domain\entities\dto.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'send_message_request.dart';