// s:\flutter\src\vtv_common\lib\src\chat\presentation\pages.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'chat_room_page.dart';
export 'chat_page.dart';