// s:\flutter\src\vtv_common\lib\src\shop\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'dto/dto.dart';
export 'shop_entity.dart';
export 'category_shop_entity.dart';