// s:\flutter\src\vtv_common\lib\src\auth\domain\entities\dto.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'register_params.dart';