// s:\flutter\src\vtv_common\lib\src\shop\presentation\pages.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'shop_detail_page.dart';