// s:\flutter\src\vtv_common\lib\src\shop\domain\entities\dto.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'shop_detail_resp.dart';